/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class chrulri_livetv_DvbTuner */

#ifndef _Included_chrulri_livetv_DvbTuner
#define _Included_chrulri_livetv_DvbTuner
#ifdef __cplusplus
extern "C" {
#endif
#undef chrulri_livetv_DvbTuner_TYPE_ATSC
#define chrulri_livetv_DvbTuner_TYPE_ATSC 1L
#undef chrulri_livetv_DvbTuner_TYPE_DVBC
#define chrulri_livetv_DvbTuner_TYPE_DVBC 2L
#undef chrulri_livetv_DvbTuner_TYPE_DVBS
#define chrulri_livetv_DvbTuner_TYPE_DVBS 3L
#undef chrulri_livetv_DvbTuner_TYPE_DVBT
#define chrulri_livetv_DvbTuner_TYPE_DVBT 4L
#undef chrulri_livetv_DvbTuner_TUNE_TIMEOUT_MS
#define chrulri_livetv_DvbTuner_TUNE_TIMEOUT_MS 2500L
/*
 * Class:     chrulri_livetv_DvbTuner
 * Method:    nativeZapStart
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_chrulri_livetv_DvbTuner_nativeZapStart
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     chrulri_livetv_DvbTuner
 * Method:    nativeZapStop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_chrulri_livetv_DvbTuner_nativeZapStop
  (JNIEnv *, jobject, jint);

/*
 * Class:     chrulri_livetv_DvbTuner
 * Method:    nativeZapStatus
 * Signature: (ILchrulri/livetv/DvbTuner/ZapStatus;)I
 */
JNIEXPORT jint JNICALL Java_chrulri_livetv_DvbTuner_nativeZapStatus
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
