/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chrulri_droidtv_DvbTuner */

#ifndef _Included_com_chrulri_droidtv_DvbTuner
#define _Included_com_chrulri_droidtv_DvbTuner
#ifdef __cplusplus
extern "C" {
#endif
#undef com_chrulri_droidtv_DvbTuner_TYPE_ATSC
#define com_chrulri_droidtv_DvbTuner_TYPE_ATSC 1L
#undef com_chrulri_droidtv_DvbTuner_TYPE_DVBC
#define com_chrulri_droidtv_DvbTuner_TYPE_DVBC 2L
#undef com_chrulri_droidtv_DvbTuner_TYPE_DVBS
#define com_chrulri_droidtv_DvbTuner_TYPE_DVBS 3L
#undef com_chrulri_droidtv_DvbTuner_TYPE_DVBT
#define com_chrulri_droidtv_DvbTuner_TYPE_DVBT 4L
#undef com_chrulri_droidtv_DvbTuner_TUNE_TIMEOUT_MS
#define com_chrulri_droidtv_DvbTuner_TUNE_TIMEOUT_MS 2500L
#undef com_chrulri_droidtv_DvbTuner_TUNE_DELAY_MS
#define com_chrulri_droidtv_DvbTuner_TUNE_DELAY_MS 250L
/*
 * Class:     com_chrulri_droidtv_DvbTuner
 * Method:    nativeZapStart
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_chrulri_droidtv_DvbTuner_nativeZapStart
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     com_chrulri_droidtv_DvbTuner
 * Method:    nativeZapStop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_chrulri_droidtv_DvbTuner_nativeZapStop
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_chrulri_droidtv_DvbTuner
 * Method:    nativeZapStatus
 * Signature: (ILcom/chrulri/droidtv/DvbTuner/ZapStatus;)I
 */
JNIEXPORT jint JNICALL Java_com_chrulri_droidtv_DvbTuner_nativeZapStatus
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
